"use client";

import Link from "next/link";
import Image from "next/image";
import { motion, useReducedMotion } from "framer-motion";
import type { Project } from "@/lib/projects";
import { getNarrative, type CaseStudyNarrative, type Feature } from "@/lib/case-studies";

const placeholderCopy = {
  overview: "Replace this with a concise overview of the project, its context, and the opportunity it addressed.",
  challenge: "Replace this with the core user, business, and technical constraints that shaped the work.",
  role: "Replace this with your responsibilities, collaborators, and the parts of the work you led.",
  process: "Replace this with the key decisions, research, explorations, and iterations that informed the final direction.",
  results: "Replace this with verified outcomes, learnings, and the impact of the work.",
};

export function AnimatedSection({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  const reduceMotion = useReducedMotion();
  return <motion.section className={className} initial={reduceMotion ? false : { opacity: 0, y: 28 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.15 }} transition={{ duration: 0.65, ease: [0.22, 1, 0.36, 1] }}>{children}</motion.section>;
}

export function LaptopMockup({ project }: { project: Project }) {
  if (project.slug === "kode-os" && project.heroImage) return <div className="kode-hero-art" style={{ "--project-accent": project.accent } as React.CSSProperties}><Image src={project.heroImage} alt={`${project.title} mobile product experience`} fill priority unoptimized sizes="(max-width: 700px) 100vw, 78vw" /></div>;
  if (project.slug === "allam" && project.heroImage) return <div className="allam-hero-art" style={{ "--project-accent": project.accent } as React.CSSProperties}><Image src={project.heroImage} alt="Allam Android AI assistant experience across chat, templates, settings, and navigation" fill priority unoptimized sizes="(max-width: 700px) 100vw, 86vw" /></div>;
  if (project.heroImage) return <div className={`hero-laptop-stage hero-${project.slug}`}><div className="laptop laptop-with-image" style={{ "--project-accent": project.accent } as React.CSSProperties}><div className="laptop-screen"><Image src={project.heroImage} alt={`${project.title} product interface`} fill priority unoptimized sizes="(max-width: 700px) 100vw, 70vw" /></div><div className="laptop-base" /></div></div>;
  return <div className="laptop" style={{ "--project-accent": project.accent } as React.CSSProperties}><div className="laptop-screen"><span className="screen-dot" /><span className="screen-line long" /><span className="screen-line" /><div className="screen-panel"><span>Screenshot placeholder</span><strong>{project.title}</strong></div><div className="screen-grid"><i /><i /><i /></div></div><div className="laptop-base" /></div>;
}

export function ScreenshotLaptopMockup({ project, src, alt }: { project: Project; src: string; alt: string }) {
  return <div className="screenshot-laptop-stage"><div className="laptop laptop-with-image" style={{ "--project-accent": project.accent } as React.CSSProperties}><div className="laptop-screen"><Image src={src} alt={alt} fill unoptimized sizes="(max-width: 700px) 100vw, 55vw" /></div><div className="laptop-base" /></div></div>;
}

export function BrowserFrame({ src, alt, className = "" }: { src: string; alt: string; className?: string }) {
  return <div className={`floating-product-card ${className}`}><div className="browser-chrome" aria-hidden="true"><span className="browser-dots"><i /><i /><i /></span><span className="browser-address">silent.ai / workspace</span><span className="browser-actions">↗　□</span></div><div className="floating-image-viewport"><Image className="floating-product-image" src={src} alt={alt} fill unoptimized sizes="(max-width: 700px) 100vw, 70vw" /></div></div>;
}

export function FloatingCard({ project, src, alt }: { project: Project; src: string; alt: string }) {
  return <div className="floating-card-stage" style={{ "--project-accent": project.accent } as React.CSSProperties}><BrowserFrame src={src} alt={alt} /></div>;
}

export function MultiScreenPresentation({ project, primary, secondary }: { project: Project; primary: string; secondary: string }) {
  return <div className="workflow-stage" style={{ "--project-accent": project.accent } as React.CSSProperties}><BrowserFrame className="workflow-primary" src={primary} alt={`${project.title} Sales-bot conversation interface`} /><BrowserFrame className="workflow-secondary" src={secondary} alt={`${project.title} assistant management interface`} /></div>;
}

export function EditorialAsset({ project, src, alt, kind = "editorial" }: { project: Project; src: string; alt: string; kind?: "editorial" | "devices" | "desktop" }) {
  const reduceMotion = useReducedMotion();
  return <motion.div className={`editorial-asset ${kind}`} style={{ "--project-accent": project.accent } as React.CSSProperties} initial={reduceMotion ? false : { opacity: 0, scale: 0.97 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true, amount: 0.15 }} transition={{ duration: 0.75, ease: [0.22, 1, 0.36, 1] }}><div className="editorial-asset-inner"><Image src={src} alt={alt} fill unoptimized sizes="(max-width: 700px) 100vw, 62vw" /></div></motion.div>;
}

function KodeResearchBoard({ src }: { src: string }) { return <div className="kode-research-board"><div className="kode-board-glow" /><div className="kode-board-card"><Image src={src} alt="KODE OS research findings" fill unoptimized sizes="(max-width: 700px) 92vw, 70vw" /></div><span>Research signals</span></div>; }
function KodePersonaCard() { return <div className="kode-persona-card"><header><span>Primary user / 01</span><h3>Sarah Johnson</h3><p>Facilities Manager overseeing operations across a commercial office complex.</p></header><div className="kode-persona-facts"><div><span>Experience</span><strong>10+ years</strong><small>Commercial property operations</small></div><div><span>Context</span><strong>Multi-building</strong><small>HVAC, lighting, security, and access</small></div></div><div className="kode-persona-columns"><section><span>Goals</span><ul><li>Keep building operations efficient and reduce downtime.</li><li>Find cost-saving opportunities through proactive maintenance.</li><li>Use real-time data to make informed decisions.</li></ul></section><section><span>Challenges</span><ul><li>Manage diverse systems and connected devices.</li><li>Turn a large volume of data into priorities.</li><li>Make confident decisions with limited time.</li></ul></section></div></div>; }
function KodeArchitecture({ src }: { src: string }) { return <div className="kode-architecture"><div className="kode-architecture-layer" /><div className="kode-architecture-board"><Image src={src} alt="KODE OS information architecture" fill unoptimized sizes="(max-width: 700px) 92vw, 72vw" /></div></div>; }
function KodeDesktopImage({ src }: { src: string }) { return <div className="kode-desktop-image"><Image src={src} alt="KODE OS desktop dashboard composition" fill unoptimized sizes="(max-width: 700px) 100vw, 78vw" /></div>; }
function KodeStyleGuide() { return <div className="kode-style-guide"><div className="kode-style-type"><span>Typography</span><strong>Operational<br />clarity.</strong><small>Confident hierarchy for dense work.</small></div><div className="kode-swatches"><span>Core palette</span><i title="Oxford Blue #002147" /><i title="Sapphire Blue #0F52BA" /><i title="Capri Blue #1B5583" /><i title="Scarlet Red #FF2400" /><i title="Kelly Green #4CBB17" /><i title="Golden Yellow #FFDF00" /></div><div className="kode-component-sample"><span>Interface states</span><button type="button">Primary action</button><b>Operational</b><em>Attention</em></div></div>; }

export function ArtifactProcessIllustration({ project, artifacts }: { project: Project; artifacts: NonNullable<CaseStudyNarrative["processArtifacts"]> }) {
  const reduceMotion = useReducedMotion();
  return <motion.div className="artifact-process" style={{ "--project-accent": project.accent } as React.CSSProperties} initial={reduceMotion ? false : { opacity: 0, scale: 0.98 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true, amount: 0.15 }} transition={{ duration: 0.75, ease: [0.22, 1, 0.36, 1] }} aria-label="Research artifacts forming the KODE OS design process"><div className="artifact-grid" /><div className="artifact-card artifact-research"><Image src={artifacts.research} alt="KODE OS research artifact" fill unoptimized sizes="(max-width: 700px) 64vw, 24vw" /></div><div className="artifact-card artifact-persona"><Image src={artifacts.persona} alt="KODE OS user persona artifact" fill unoptimized sizes="(max-width: 700px) 54vw, 22vw" /></div><div className="artifact-card artifact-sitemap"><Image src={artifacts.sitemap} alt="KODE OS site map artifact" fill unoptimized sizes="(max-width: 700px) 72vw, 31vw" /></div><span className="artifact-label label-research">01 / Research</span><span className="artifact-label label-model">02 / Model</span><span className="artifact-label label-handoff">03 / Handoff</span><i className="artifact-line line-one" /><i className="artifact-line line-two" /></motion.div>;
}

function KodeProcessFlow({ steps }: { steps: string[] }) {
  const reduceMotion = useReducedMotion();
  return <motion.div className="kode-process-flow kode-process-image" initial={reduceMotion ? false : { opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }} aria-label={`KODE OS design process: ${steps.join(", ")}`}><Image src="/assets/projects/kode-os/process-loop-dark.png" alt="Empathize, define, ideate, prototype, and test design process loop" fill unoptimized sizes="(max-width: 700px) 100vw, 70vw" /></motion.div>;
}

function AllamProcessFlow() {
  const reduceMotion = useReducedMotion();
  return <motion.div className="allam-process-flow" initial={reduceMotion ? false : { opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }}><Image src="/assets/projects/allam/allam-design-process.png" alt="Allam design process showing research, define, design, prototype, and validate" fill unoptimized sizes="(max-width: 700px) 100vw, 70vw" /></motion.div>;
}

function AllamProductJourney({ src }: { src: string }) {
  const reduceMotion = useReducedMotion();
  return <motion.div className="allam-product-journey" initial={reduceMotion ? false : { opacity: 0, scale: 0.98 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true, amount: 0.15 }} transition={{ duration: 0.75, ease: [0.22, 1, 0.36, 1] }}><Image src={src} alt="Allam mobile journey across chat, exploration, conversations, navigation, and settings" fill unoptimized sizes="(max-width: 700px) 100vw, 76vw" /></motion.div>;
}

export function ImageSection({ project, label, variant = "wide" }: { project: Project; label: string; variant?: "wide" | "portrait" | "split" }) {
  const reduceMotion = useReducedMotion();
  return <motion.div className={`image-placeholder ${variant}`} style={{ "--project-accent": project.accent } as React.CSSProperties} initial={reduceMotion ? false : { clipPath: "inset(8% 5% 8% 5%)", scale: 0.96 }} whileInView={{ clipPath: "inset(0% 0% 0% 0%)", scale: 1 }} viewport={{ once: true, amount: 0.15 }} transition={{ duration: 0.8, ease: [0.22, 1, 0.36, 1] }}><span>{label}</span><small>Replace with /public/assets/projects/{project.slug}/...</small><div className="image-ui"><i /><i /><i /></div></motion.div>;
}

export function DesignProcessIllustration() {
  const reduceMotion = useReducedMotion();
  return <motion.div className="process-illustration" initial={reduceMotion ? false : { opacity: 0, scale: 0.98 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.75, ease: [0.22, 1, 0.36, 1] }} aria-label="Abstract illustration of the product design process"><div className="process-grid" /><div className="process-frame research-card"><span>01</span><b>Signals</b><i /><i /><i /></div><div className="process-note">Research<br />patterns</div><div className="process-connector connector-one" /><div className="process-frame flow-card"><span>02</span><b>Flows</b><div><i /><i /><i /></div></div><div className="process-connector connector-two" /><div className="process-frame system-card"><span>03</span><b>System</b><div><i /><i /><i /><i /></div></div><div className="process-token token-one">space / 24</div><div className="process-token token-two">state / ready</div><div className="process-frame handoff-card"><span>04</span><b>Build</b><em>↗</em></div></motion.div>;
}

export function ProjectHero({ project, introduction }: { project: Project; introduction?: string }) {
  const metadata = project.metadata ?? [{ label: "Role", value: project.role }, { label: "Timeline", value: project.timeline }, { label: "Platform", value: project.platform }, { label: "Technologies", value: project.technologies.join(" · ") }];
  return <section className="case-hero"><div className="case-hero-head"><p className="eyebrow">{project.number} / {project.category}</p><h1>{project.title}</h1><p className="case-subtitle">{project.subtitle}</p>{introduction && <p className="case-introduction">{introduction}</p>}</div><div className="project-meta">{metadata.map((item) => <div key={item.label}><span>{item.label}</span><strong>{item.value}</strong></div>)}</div><LaptopMockup project={project} /><a className="scroll-indicator" href="#overview">Scroll to explore <b>↓</b></a></section>;
}

function ContentSection({ number, title, children }: { number: string; title: React.ReactNode; children: React.ReactNode }) {
  return <AnimatedSection className="case-section"><p className="section-number">{number}</p><div><h2>{title}</h2><div className="case-copy">{children}</div></div></AnimatedSection>;
}

function caseTitle(narrative: CaseStudyNarrative | null | undefined, key: keyof NonNullable<CaseStudyNarrative["headings"]>, fallback: React.ReactNode) { const heading = narrative?.headings?.[key]; return heading ? <>{heading[0]}<br /><em>{heading[1]}</em></> : fallback; }

export function ProjectOverview({ narrative }: { narrative?: CaseStudyNarrative | null }) {
  return <ContentSection number="01 / Overview" title={caseTitle(narrative, "overview", narrative ? <>A trusted layer<br />for <em>company knowledge.</em></> : "The project, at a glance.")}>{narrative ? <>{narrative.overview.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{narrative.overviewCards && <div className="overview-cards">{narrative.overviewCards.map((card) => <section key={card.title}><span>{card.title}</span><p>{card.text}</p></section>)}</div>}</> : <p>{placeholderCopy.overview}</p>}</ContentSection>;
}
export function ProjectChallenge({ narrative }: { narrative?: CaseStudyNarrative | null }) {
  return <ContentSection number="02 / Challenge" title={caseTitle(narrative, "challenge", <>Making complexity feel <em>legible.</em></>)}>{narrative ? narrative.challenge.map((paragraph) => <p key={paragraph}>{paragraph}</p>) : <p>{placeholderCopy.challenge}</p>}</ContentSection>;
}
export function ProjectRole({ narrative }: { narrative?: CaseStudyNarrative | null }) {
  return <ContentSection number="03 / Role" title={caseTitle(narrative, "role", narrative ? <>Designing the<br /><em>system behind trust.</em></> : "A focused role in a shared effort.")}>{narrative ? <div className="role-cards">{narrative.roleCards.map((role) => <div key={role}>{role}</div>)}</div> : <><p>{placeholderCopy.role}</p><ul><li>Placeholder responsibility</li><li>Placeholder collaboration</li><li>Placeholder deliverable</li></ul></>}</ContentSection>;
}
export function ProjectProcess({ project, narrative }: { project: Project; narrative?: CaseStudyNarrative | null }) {
  return <ContentSection number="04 / Process" title={caseTitle(narrative, "process", narrative ? <>A deliberate path<br />from unknowns to <em>clarity.</em></> : "From signals to a clearer system.")}>{narrative ? <><p>{narrative.processIntro ?? "Each phase gave the team a shared way to turn enterprise complexity into decisions that could be tested, implemented, and scaled."}</p><ol className="process-timeline">{narrative.processSteps.map((step, index) => <li key={step}><span>{String(index + 1).padStart(2, "0")}</span>{step}</li>)}</ol>{project.slug === "kode-os" ? <KodeProcessFlow steps={narrative.processSteps} /> : project.slug === "allam" ? <AllamProcessFlow /> : narrative.processArtifacts ? <ArtifactProcessIllustration project={project} artifacts={narrative.processArtifacts} /> : <DesignProcessIllustration />}</> : <><p>{placeholderCopy.process}</p><ImageSection project={project} label="Research & early explorations" /></>}</ContentSection>;
}
export function ProjectFeature({ project, index, feature }: { project: Project; index: number; feature?: Feature }) { const sectionNumber = String(index).padStart(2, "0"); return <AnimatedSection className={`feature-section ${project.slug === "allam" ? "allam-feature" : ""} feature-${feature?.presentation ?? "default"} ${feature?.layout === "centered" ? "feature-centered" : index % 2 === 0 ? "image-left" : ""}`}><div className="feature-copy"><p className="section-number">{sectionNumber} / {feature ? "Product feature" : "Feature"}</p><h2>{feature ? <>{feature.title}<br /><em>by design.</em></> : <>Feature story<br /><em>placeholder.</em></>}</h2>{feature ? <><p><strong>Problem</strong>{feature.problem}</p><p><strong>Solution</strong>{feature.solution}</p></> : <p>Replace this with the problem, interaction, and design decision behind a specific feature.</p>}</div>{feature?.presentation === "persona" ? <KodePersonaCard /> : feature?.screenshot ? feature.presentation === "allam-journey" ? <AllamProductJourney src={feature.screenshot} /> : feature.presentation === "multi-screen" && feature.secondaryScreenshot ? <MultiScreenPresentation project={project} primary={feature.screenshot} secondary={feature.secondaryScreenshot} /> : feature.presentation === "floating-card" ? <FloatingCard project={project} src={feature.screenshot} alt={`${project.title} ${feature.title} configuration`} /> : feature.presentation === "research" ? <KodeResearchBoard src={feature.screenshot} /> : feature.presentation === "architecture" ? <KodeArchitecture src={feature.screenshot} /> : feature.presentation === "style-guide" ? <KodeStyleGuide /> : feature.presentation === "desktop" ? <KodeDesktopImage src={feature.screenshot} /> : feature.presentation === "editorial" || feature.presentation === "devices" ? <EditorialAsset project={project} src={feature.screenshot} alt={`${project.title} ${feature.title} artifact`} kind={feature.presentation} /> : <ScreenshotLaptopMockup project={project} src={feature.screenshot} alt={`${project.title} ${feature.title} interface`} /> : <>{/* TODO: Replace this mockup with the corresponding original Allam screenshot. */}<ImageSection project={project} label={feature ? `${feature.title} — original screens pending` : `Feature ${index} screenshot`} variant={feature?.variant ?? (index % 2 === 0 ? "portrait" : "split")} /></>}</AnimatedSection>; }
export function ProjectGallery({ project }: { project: Project }) { return <AnimatedSection className="gallery-section"><div><p className="section-number">07 / Gallery</p><h2>Moments from<br />the <em>interface.</em></h2></div><div className="gallery-grid"><ImageSection project={project} label="Gallery image 01" variant="portrait" /><ImageSection project={project} label="Gallery image 02" variant="portrait" /><ImageSection project={project} label="Gallery image 03" /></div></AnimatedSection>; }
export function DesignSystemShowcase({ items, variant }: { items: string[]; variant?: "kode" | "allam" }) { const isAllam = variant === "allam"; return <div className={`design-system-showcase ${variant ? `${variant}-system-showcase` : ""}`}><section><span className="showcase-label">Typography</span><div className="type-samples"><strong>Aa</strong><div><b>Product UI / Display</b><span>{isAllam ? "Clear hierarchy for conversational Android flows." : "Clear hierarchy for dense enterprise workflows."}</span></div></div></section><section><span className="showcase-label">Semantic colors</span><div className="color-swatches"><i /><i /><i /><i /><i /></div></section><section className="showcase-components"><span className="showcase-label">Components</span><div><button type="button">Primary action</button><input aria-label="Example input" value={isAllam ? "Ask Allam" : "Search datasets"} readOnly /><em>Ready</em><em className="warning">{isAllam ? "Listening" : "Queued"}</em></div></section><section><span className="showcase-label">Tokens</span><div className="token-list">{items.map((item) => <span key={item}>{item}</span>)}</div></section></div>; }
export function ProjectDesignSystem({ project, narrative }: { project: Project; narrative?: CaseStudyNarrative | null }) { const number = narrative ? String(narrative.features.length + 5).padStart(2, "0") : "08"; const variant = project.slug === "kode-os" ? "kode" : project.slug === "allam" ? "allam" : undefined; return <AnimatedSection className="design-system"><div><p className="section-number">{number} / Design system</p><h2>{caseTitle(narrative, "designSystem", narrative ? <>Designed to<br /><em>hold together.</em></> : <>Built for<br /><em>consistency.</em></>)}</h2></div><div><p>{narrative?.designSystem ?? "Replace this with the principles, components, tokens, and governance behind the project’s design system."}</p>{narrative ? <DesignSystemShowcase items={narrative.designSystemItems} variant={variant} /> : <ImageSection project={project} label="Design system overview" />}</div></AnimatedSection>; }
export function ProjectResults({ narrative }: { narrative?: CaseStudyNarrative | null }) { const number = narrative ? String(narrative.features.length + 6).padStart(2, "0") : "09"; return <ContentSection number={`${number} / ${narrative ? "Impact" : "Results"}`} title={caseTitle(narrative, "results", narrative ? <>A stronger system<br />for <em>moving work forward.</em></> : "What moved forward.")}>{narrative ? <><p>These outcomes describe the product and design foundation created through the work. They intentionally avoid unverified performance metrics.</p><div className="results-grid outcomes-grid">{narrative.outcomes.map((outcome, index) => <div key={outcome}><strong>{String(index + 1).padStart(2, "0")}</strong><span>{outcome}</span></div>)}</div></> : <><p>{placeholderCopy.results}</p><div className="results-grid"><div><strong>—</strong><span>Metric placeholder</span></div><div><strong>—</strong><span>Metric placeholder</span></div><div><strong>—</strong><span>Outcome placeholder</span></div></div></>}</ContentSection>; }
export function ProjectNextProject({ project, nextProject }: { project: Project; nextProject: Project }) { return <section className="next-project"><p className="eyebrow">Next project</p><Link href={`/projects/${nextProject.slug}`}><span>{nextProject.number}</span><h2>{nextProject.title}<br /><em>{nextProject.category}</em></h2><b>↗</b></Link><Link className="back-work" href="/#work">Back to selected work</Link></section>; }

export function CaseStudyPage({ project, nextProject }: { project: Project; nextProject: Project }) {
  const narrative = getNarrative(project);
  return <main className="case-study"><header className="site-header case-header"><Link href="/" className="wordmark" aria-label="Back to homepage">NM<span>•</span></Link><nav aria-label="Case study navigation"><Link href="/#work">All work</Link><Link href="/#contact">Contact</Link></nav></header><ProjectHero project={project} introduction={narrative?.introduction} /><div id="overview"><ProjectOverview narrative={narrative} /><ProjectChallenge narrative={narrative} /><ProjectRole narrative={narrative} /><ProjectProcess project={project} narrative={narrative} />{narrative ? narrative.features.map((feature, index) => <ProjectFeature key={feature.title} project={project} feature={feature} index={index + 5} />) : <><ProjectFeature project={project} index={5} /><ProjectFeature project={project} index={6} /><ProjectGallery project={project} /></>}<ProjectDesignSystem project={project} narrative={narrative} /><ProjectResults narrative={narrative} /></div><ProjectNextProject project={project} nextProject={nextProject} /></main>;
}
